### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by lumosnysm** [ModuledkQuy/Quiz_Blockchain#36]
- Player can expand their limited time of each question, for example 10 second will cost 1 ETH.
- Change the game structure, from picking a answer to bet money on all the answers, for example there will be 4 answers A, B, C, D:
    + The current gameplay: picking 1 answer and then submit, player will earn money if that answer is right.
    + The new gameplay: player will bet money on all the answers, for example A: 1 ETH, B: 2 ETH, C: 3 ETH, D: 4 ETH and if C is the right answer player will earn 3 ETH and lose 1 + 2 + 4 = 7 ETH.

Note: 
- With the current gameplay, if the player pick the right answer, we'll get nothing.
- With the new gameplay, we wil get money even when the player have the right answer, depend on player's betting ratio.
@ModuledkQuy

**Comment by ModuledkQuy** [comment]
+I don't understand this "With the current gameplay, if the player pick the right answer, we'll get nothing."
Can you describe it clearly.

+I think it will be better if players have to put ether in each answer, the ether must greater than zero. 
+We will have many packets for buying time. Forexample, 1ETH for packet 10 second.

@lumosnysm

**Comment by lumosnysm** [comment]
- i mean with the current gameplay, if player submit a right answer we have to pay them, we will not making any money unless the player submit a wrong answer(or timeout), and with the new gameplay, this game is much more like a gambling game, i think it in somehow good for both.
- And yes i think we will make a limit range of ether in each answer.

**Comment by ModuledkQuy** [comment]
I did change mind my, players will bet money before they submit quiz and yah, we will not take users' money when getting new quiz.

**Comment by lumosnysm** [comment]
exactly wat i think
