### ISSUE TITLE
Use the time which player buy like a kind of money.

### ISSUE THREAD

**Issue by lumosnysm** [ModuledkQuy/Quiz_Blockchain#39]
- now  we don't give player 30 s for each question, they have to buy time before taking a question, and that time will be stored in player's account like a kind of wallet, they can use it through every question they take till the time is run out and then they have to buy more time to take the next question.

**Comment by lumosnysm** [comment]
should we do that ?
@ModuledkQuy

**Comment by ModuledkQuy** [comment]
yep
