### ISSUE TITLE
tasks

### ISSUE THREAD

**Issue by ModuledkQuy** [ModuledkQuy/Quiz_Blockchain#44]
1. Khi submit.
+ Nhận event trả về đáp án đúng.
+ Sau đó xử lý giao dịch trên web3js tại phía clients.
+ Phải bet hết thì mới được submit và lượng tài sản bet trong khoảng (0,1)
-> all things are done.
-> using interface to display ether and test.

2. Khi mua thời gian và xác nhận OK.
* Điều kiện: Câu hỏi chưa được trả lời và còn đủ tiền để mua.

+ Count thời gian tới âm vì không thì nó sẽ có thể sai phạm, nó có thể dùng thiết bị khác để tra câu hỏi. -> done.
+ Cần phải giảm thời gian để tránh bị tra câu hỏi.
-> done. 30s maybe allright.
+ Gửi lên server lượng thời gian mua theo các gói lưu trữ.
+ Cập nhập sessionStorage in client timer và cập nhập timer.
+ Thực thi giao dịch tức trừ tiền.
+chỉ mua lúc chơi.
+các gói câu hỏi sẽ hiển thị ở phần đang chơi bên cạnh thời gian, một hàng trên đó.

**Comment by lumosnysm** [comment]
ok, đang lười quá, thứ 7 chủ nhật sẽ làm

**Comment by ModuledkQuy** [comment]
done.
