### ISSUE TITLE
Writing Report 

### ISSUE THREAD

**Issue by ModuledkQuy** [ModuledkQuy/Quiz_Blockchain#5]
+ Writing the idea of project in report.

**Comment by ModuledkQuy** [comment]
You should add the link of the report you wrote here, so I can check again the report.
The description should be clear about the project:
+ Have limit question (about 10, 100, or thousands of them) in a day for everyone answer together.

**Comment by ModuledkQuy** [comment]
Add link to the report here @lumosnysm

**Comment by lumosnysm** [comment]
https://docs.google.com/document/d/1pBpZOeFmYzkDKGuV6qlqTFsz-ICSyM2SkkzGNc9H90M/edit#heading=h.374wbeydnp1v @ModuledkQuy

**Comment by ModuledkQuy** [comment]
I've updated somethings in the report, you can check again and provide some more info if necessary. @lumosnysm
